version: "3.8"

services:
  api:
    build:
      context: ../core
      dockerfile: Dockerfile
    volumes:
      - ../core:/app:cached
      - saleor-media:/app/media
    image: null

  worker:
    build:
      context: ../core
      dockerfile: Dockerfile
    command: celery -A saleor --app=saleor.celeryconf:app worker --loglevel=info -B
    volumes:
      - ../core:/app:cached
      - saleor-media:/app/media
    image: null

  dashboard:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ../dashboard:/app:cached
    ports:
      - "9001:9000"
    command: sh -c "corepack enable && corepack prepare yarn@stable --activate && yarn install && yarn dev"
    environment:
      VITE_API_URL: http://localhost:8000/graphql/
      PORT: "9000"
